config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/" => "homes#top",as: "top"
  get "/home/about" => "homes#about", as: "about"
  resources :books, only: [:create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:show, :edit, :update, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }



  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
    flash[:notice] = "successfully投稿に成功しました。"
    redirect_to book_path(@book.id)
    else
    @books = Book.all
    render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user

  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = current_user
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @user = current_user
    if @book.update(book_params)
    flash[:notice] = "successfully更新に成功しました。"
    redirect_to book_path(@book)
    else
    render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:deleted] = "successfully削除に成功しました。"
    redirect_to book
  end


  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    user = book.user
    unless user.id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
  @user = User.find(params[:id])
  puts @user.inspect
  @books = @user.books
  @book = Book.new
  end


  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "successfullyユーザー情報を更新しました"
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "successfullyユーザー情報の更新に失敗しました"
      render :edit
    end
  end

 before_action :set_user, only: [:show, :edit, :update, :destroy]

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_image_helper.rb
module PostImageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_errors.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/books/_list.html.erb
<label for="book_title">Title</label>
<div><%= form.text_field :title %></div>
<h4>Opinion</h4>
<div><%= form.text_area :body %></div>
<div><%= form.submit 'Create Book' %></div>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>
<% end %>
<%= link_to "Show", @book %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h1>User info</h1>
        <%= image_tag @user.get_profile_image(100,100) %>
        <table class="table">
          <thead>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </thead>
        </table>
        <div class="row">
          <%= link_to edit_user_path(@user) do %>
            <i class="fa-solid fa-user-gear"></i>
          <% end %>
        </div>
        
        <h2 class="mt-3">New book</h2>
          <%= render 'books/errors', book: @book %>
          <%= form_with(model: @book, url: books_path) do |form| %>
            <%= render 'books/list', form: form %>
          <% end %>
      </div>
    
    
      <div class="col-md-8 offset-md-1">
        <div class="row">
          <h1>Books</h1>
        </div>
        <div class="row">
          <table>
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
              </tr>
            </thead>
            <tbody>
              <% @books.each do |book| %>
                <tr>
                  <td>
                    <%= link_to user_path(book.user) do %>
                      <%= image_tag(book.user.get_profile_image(100,100)) %>
                    <% end %>
                    <%= book.user.name %>
                  </td>
                  <td><%= link_to book.title, book_path(book) %></td>
                  <td><%= book.body %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/books/show.html.erb
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h1>User info</h1>
        <%= image_tag @user.get_profile_image(100,100) %>
        <table class="table">
          <thead>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </thead>
        </table>
        <div class="row">
          <%= link_to edit_user_path(@user) do %>
            <i class="fa-solid fa-user-gear"></i>
          <% end %>
        </div>
        <h2 class="mt-3">New book</h2>

          <%= render 'errors', book: @book %>
          <%= form_with(model: @book_new) do |form| %>
            <%= render 'list', form: form %>
          <% end %>

      </div>

      <div class="col-md-8 offset-md-1">
        <div class="row">
          <h1>Book detail</h1>
        </div>
        <div class="row">
          <table>
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <%= link_to @user do %>
                    <%= image_tag(@user.get_profile_image(100,100)) %>
                    <%= link_to @book.user.name, user_path(@book.user) %>
                  <% end %>

                </td>
                <td>
                  <%= link_to @book.title, book_path(@book) %>
                  <%= @book.body %>
                </td>
              </tr>
              <tr>
                <% if @book.user == current_user %>
                <td>
                  <%= link_to "Edit", edit_book_path(@book.id) %></td>
                  <%= link_to "Destroy", book_path(@book), method: :delete , "data-confirm" => "本当に削除しますか？" %>
                <% end %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/homes/about.html.erb
<h1>Aboutページ</h1>
<i class="fas fa-book"></i>

app/views/homes/top.html.erb
<div>
  <%= flash[:notice] %>
</div>
<h1>TOPページ</h1>
<i class="fas fa-book"></i>
  <%= link_to 'Log in', new_user_session_path, class: "btn btn-info log-in" %>
  <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-success sign-up" %>

app/views/layouts/_list.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @book, url: books_path) do |form| %>
  <h4>Title</h4>
  <%= form.text_field :title %>
  <h4>Body</h4>
  <%= form.text_area :body %>
  <%= form.submit 'Create Book' %>
<% end %>



<% if book.errors.any? %>
  <%= book.errors.count %>件のerrorが発生しました
  <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: book, url: books_path) do |form| %>
  <h4>Title</h4>
  <%= form.text_field :title %>
  <h4>Body</h4>
  <%= form.text_area :body %>
  <%= form.submit 'Create Book' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/c0cf8a90ba.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


 <body class="d-flex flex-column vh-100">
   <script src="https://kit.fontawesome.com/c0cf8a90ba.js" crossorigin="anonymous"></script>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <ul>
            <%= link_to "Bookers" , top_path %>
          </ul>
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <i class="fa-solid fa-house"></i>
              <%= link_to "Home", new_user_session_url %>
            </li>
            <li class="nav-item">
              <i class="fa-solid fa-users"></i>
              <%= link_to "Users" ,users_path %>
            </li>
            <li class="nav-item">
              <i class="fas fa-book-open"></i>
              <%= link_to "Books", books_path %>
            </li>
            <li class="nav-item">
              <i class="fa-solid fa-right-from-bracket"></i>
              <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            </li>
            <% else %>
            <li class="nav-item">
              <i class="fa-solid fa-house"></i>
              <%= link_to "Home" ,  top_path %>
            </li>
            <li class="nav-item">
              <i class="fa-solid fa-link"></i>
              <%= link_to "About", about_path %>
            </li>
            <li class="nav-item">
              <i class="fa-solid fa-user-plus"></i>
              <%= link_to "Sign up", new_user_registration_path %>
            </li>
            <li class="nav-item">
              <i class="fa-solid fa-right-to-bracket"></i>
              <%= link_to "Log in", new_user_session_path %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <p id = "notice"><%= notice %></p>
    <%= yield %>
    </main>
  </body>

app/views/shared/error.html.erb
<% if book.errors.any? %>
  <%= book.errors.count %>件のerrorが発生しました
  <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/newbook.html.erb
<%= form_with(model: book, url: books_path) do |form| %>
  <h4>Title</h4>
  <%= form.text_field :title %>
  <h4>Body</h4>
  <%= form.text_area :body %>
  <%= form.submit 'Create Book' %>
<% end %>

app/views/users/edit.html.erb
<h1>User info</h1>
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のerrorが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">Image</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  <label for="inputIntroduction">Introduction</label>
  <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介文"%>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h1>User info</h1>
        <%= image_tag @user.get_profile_image(100,100) %>
        <table class="table">
          <thead>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </thead>
        </table>
        <div class="row">
          <%= link_to edit_user_path(@user) do %>
            <i class="fa-solid fa-user-gear"></i>
          <% end %>
        </div>
        
        <h2 class="mt-3">New book</h2>
          <%= render 'books/errors', book: @book %>
          <%= form_with(model: @book, url: books_path) do |form| %>
            <%= render 'books/list', form: form %>
          <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <div class="row">
          <h1>Users</h1>
        </div>
        <div class="row">
          <table>
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
              <tr>
                <td>
                    <%= image_tag user.get_profile_image(100,100), fallback: "sample-author1" %>
                    <%= user.name %>
                    <%= link_to "Show", user_path(user) %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/users/show.html.erb
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h1>User info</h1>
        <%= image_tag @user.get_profile_image(100,100) %>
        <table class="table">
          <thead>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </thead>
        </table>
        <div class="row">
          <%= link_to edit_user_path(@user) do %>
            <i class="fa-solid fa-user-gear"></i>
          <% end %>
        </div>
        
        <h2 class="mt-3">New book</h2>
          <%= render 'books/errors', book: @book %>
          <%= form_with(model: @book, url: books_path) do |form| %>
            <%= render 'books/list', form: form %>
          <% end %>
      </div>
  
    
      <div class="col-md-8 offset-md-1">
        <div class="row">
          <h1>Books</h1>
        </div>
        <div class="row">
          <table>
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
              </tr>
            </thead>
            <tbody>
              <% @books.each do |book| %>
                <tr>
                  <td>
                    <%= link_to book.user do %>
                      <%= image_tag(book.user.get_profile_image(100,100)) %>
                    <% end %>
                    <%= book.user.name %>
                  </td>
                  <td><%= link_to book.title, book_path(book) %></td>
                  <td><%= book.body %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</body>